version: 1
services:
  - type: web
    name: your-service-name
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    build:
      commands:
        - npm install
        - npx prisma generate
        - npx prisma migrate deploy
